"""
Configuration for AlbertMohler YouTube Semantic Search Project

This file contains all project-specific settings.
Import from this file in your scripts:

    from config import CHANNEL_HANDLE, CHANNEL_ID, VIDEO_IDS_DIR, PINECONE_INDEX

Generated by yt_ai_search_setup_v5.sh on 2025-12-30
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# =============================================================================
# PROJECT SETTINGS
# =============================================================================
PROJECT_NAME = "AlbertMohler"
PROJECT_SLUG = "albertmohler"  # Lowercase, hyphenated (for wp-plugin, etc.)
PROJECT_ROOT = Path(__file__).parent

# =============================================================================
# YOUTUBE CHANNEL SETTINGS
# =============================================================================
CHANNEL_HANDLE = "@AlbertMohlerOfficial"
CHANNEL_ID = "UCzH05TIlVgb3fNFMb10LYvg"  # Empty string if not provided
CHANNEL_DISPLAY_NAME = "Albert Mohler"
CHANNEL_URL = "https://www.youtube.com/channel/UCzH05TIlVgb3fNFMb10LYvg"

# =============================================================================
# PINECONE SETTINGS
# =============================================================================
PINECONE_INDEX = "mohler-youtube"
PINECONE_NAMESPACE = "youtube"

# =============================================================================
# API KEYS (loaded from .env)
# =============================================================================
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")

# Webshare Proxy (for transcript extraction)
WEBSHARE_PROXY_USERNAME = os.getenv("WEBSHARE_PROXY_USERNAME")
WEBSHARE_PROXY_PASSWORD = os.getenv("WEBSHARE_PROXY_PASSWORD")

# =============================================================================
# SERVER SETTINGS (for Flask API)
# =============================================================================
SERVER_PORT = int(os.getenv("SERVER_PORT", "5007"))

# API Keys for server authentication (comma-separated in .env)
API_KEY_POC = os.getenv("API_KEY_POC", "poc-dev-key-change-me")
API_KEY_WORDPRESS = os.getenv("API_KEY_WORDPRESS", "")

# Admin dashboard credentials
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "change-me-in-production")

# CORS allowed origins (comma-separated in .env, or empty for localhost only)
_origins = os.getenv("ALLOWED_ORIGINS", "")
ALLOWED_ORIGINS = [o.strip() for o in _origins.split(",") if o.strip()] if _origins else []

# =============================================================================
# DIRECTORY PATHS
# =============================================================================
DATA_DIR = PROJECT_ROOT / "data"
LOGS_DIR = PROJECT_ROOT / "logs"
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
SERVER_DIR = PROJECT_ROOT / "server"
WP_PLUGIN_DIR = PROJECT_ROOT / "wp-plugin" / f"{PROJECT_SLUG}-ai-search"

# Data subdirectories
VIDEO_IDS_DIR = DATA_DIR / "video_ids"
METADATA_DIR = DATA_DIR / "metadata"
TRANSCRIPTS_DIR = DATA_DIR / "transcripts"
CHUNKS_DIR = DATA_DIR / "chunks"
EMBEDDINGS_DIR = DATA_DIR / "embeddings"

# Server subdirectories
SERVER_STATIC_DIR = SERVER_DIR / "static"
SERVER_DATA_DIR = SERVER_DIR / "data"

# WordPress plugin subdirectories
WP_PLUGIN_INCLUDES_DIR = WP_PLUGIN_DIR / "includes"
WP_PLUGIN_PUBLIC_DIR = WP_PLUGIN_DIR / "public"
WP_PLUGIN_ADMIN_DIR = WP_PLUGIN_DIR / "admin"

# =============================================================================
# OUTPUT FILE PATHS
# =============================================================================
VIDEO_IDS_FILE = VIDEO_IDS_DIR / "all_video_ids.json"
VIDEO_IDS_ONLY_FILE = VIDEO_IDS_DIR / "video_ids_only.txt"
METADATA_FILE = METADATA_DIR / "video_metadata.json"
CHUNKS_FILE = CHUNKS_DIR / "all_chunks.json"
EMBEDDINGS_FILE = EMBEDDINGS_DIR / "youtube_embeddings.json"

# Progress tracking files
TRANSCRIPT_PROGRESS_FILE = TRANSCRIPTS_DIR / "progress.json"
CHUNKS_PROGRESS_FILE = CHUNKS_DIR / "chunking_progress.json"
EMBEDDINGS_PROGRESS_FILE = EMBEDDINGS_DIR / "embedding_progress.json"

# Server files
ANALYTICS_DB_FILE = SERVER_DATA_DIR / "analytics.db"

# =============================================================================
# PROCESSING SETTINGS
# =============================================================================

# Chunking parameters
TARGET_CHUNK_DURATION = 75    # seconds (aim for 60-90)
MIN_CHUNK_DURATION = 45       # Don't create chunks shorter than this
MAX_CHUNK_DURATION = 120      # Don't let chunks exceed this

# Embedding settings
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMENSIONS = 1536
EMBEDDING_BATCH_SIZE = 100

# Transcript extraction settings
TRANSCRIPT_DELAY = 2.0        # Delay between requests (seconds)
TRANSCRIPT_MAX_RETRIES = 3

# Pinecone upload settings
PINECONE_BATCH_SIZE = 100

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def ensure_directories():
    """Create all necessary directories if they don't exist."""
    for directory in [VIDEO_IDS_DIR, METADATA_DIR, TRANSCRIPTS_DIR, 
                      CHUNKS_DIR, EMBEDDINGS_DIR, LOGS_DIR,
                      SERVER_STATIC_DIR, SERVER_DATA_DIR,
                      WP_PLUGIN_INCLUDES_DIR, 
                      WP_PLUGIN_PUBLIC_DIR / "css",
                      WP_PLUGIN_PUBLIC_DIR / "js",
                      WP_PLUGIN_ADMIN_DIR / "js"]:
        directory.mkdir(parents=True, exist_ok=True)


def validate_api_keys():
    """Check if required API keys are set."""
    missing = []
    if not YOUTUBE_API_KEY:
        missing.append("YOUTUBE_API_KEY")
    if not OPENAI_API_KEY:
        missing.append("OPENAI_API_KEY")
    if not PINECONE_API_KEY:
        missing.append("PINECONE_API_KEY")
    return missing


def validate_server_config():
    """Check if server configuration is complete."""
    issues = []
    if ADMIN_PASSWORD == "change-me-in-production":
        issues.append("ADMIN_PASSWORD is default value")
    if API_KEY_POC == "poc-dev-key-change-me":
        issues.append("API_KEY_POC is default value")
    return issues


def get_log_file(script_name):
    """Get log file path for a script."""
    return LOGS_DIR / f"{script_name}.log"


# Print config summary when imported directly
if __name__ == "__main__":
    print(f"Project: {PROJECT_NAME}")
    print(f"Channel: {CHANNEL_DISPLAY_NAME} ({CHANNEL_HANDLE})")
    print(f"Pinecone: {PINECONE_INDEX} / {PINECONE_NAMESPACE}")
    print(f"Server Port: {SERVER_PORT}")
    print(f"Project Root: {PROJECT_ROOT}")
    print()
    missing = validate_api_keys()
    if missing:
        print(f"⚠ Missing API keys: {', '.join(missing)}")
        print("  Add them to your .env file")
    else:
        print("✓ All API keys configured")
    print()
    issues = validate_server_config()
    if issues:
        print(f"⚠ Server config issues: {', '.join(issues)}")
    else:
        print("✓ Server configuration looks good")
