"""
AlbertMohler - YouTube Semantic Search API
============================================================

Flask server for semantic search across Albert Mohler's YouTube transcripts.

Endpoints:
  GET  /                    - Search interface
  GET  /api/v1/health       - Health check
  POST /api/v1/search       - Search transcripts
  POST /api/v1/summarize    - AI summary
  GET  /api/v1/stats        - Index statistics
  GET  /admin               - Admin dashboard

Generated by 07_local_POC_v1.py
"""

import os
import sys
import json
import hashlib
import time
import threading
from pathlib import Path
from datetime import datetime, timedelta
from collections import OrderedDict
from functools import wraps

from flask import Flask, request, jsonify, send_from_directory, Response, Blueprint
from flask_cors import CORS
from dotenv import load_dotenv
import sqlite3

# =============================================================================
# PATH SETUP - Import from parent config.py
# =============================================================================
SERVER_DIR = Path(__file__).parent
PROJECT_ROOT = SERVER_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Load environment variables from project root
load_dotenv(PROJECT_ROOT / ".env")

# Import configuration
from config import (
    CHANNEL_HANDLE, CHANNEL_DISPLAY_NAME,
    PINECONE_INDEX, PINECONE_NAMESPACE,
    SERVER_PORT, ALLOWED_ORIGINS,
    API_KEY_POC, API_KEY_WORDPRESS,
    ADMIN_USERNAME, ADMIN_PASSWORD,
    EMBEDDING_MODEL,
    OPENAI_API_KEY, PINECONE_API_KEY,
)

# =============================================================================
# FLASK APP SETUP
# =============================================================================
app = Flask(__name__, static_folder='static')

# Configure CORS
cors_origins = ALLOWED_ORIGINS + ["http://localhost:5005", "http://127.0.0.1:5005"]
CORS(app, origins=cors_origins if cors_origins else "*")

# Create API Blueprint
api_v1 = Blueprint('api_v1', __name__, url_prefix='/api/v1')

# =============================================================================
# EXTERNAL CLIENTS (lazy initialization)
# =============================================================================
_pinecone_index = None
_openai_client = None


def get_pinecone_index():
    """Lazy initialization of Pinecone client."""
    global _pinecone_index
    if _pinecone_index is None:
        try:
            from pinecone import Pinecone
            pc = Pinecone(api_key=PINECONE_API_KEY)
            _pinecone_index = pc.Index(PINECONE_INDEX)
            print(f"✓ Connected to Pinecone index: {PINECONE_INDEX}")
        except Exception as e:
            print(f"✗ Pinecone connection failed: {e}")
            raise
    return _pinecone_index


def get_openai_client():
    """Lazy initialization of OpenAI client."""
    global _openai_client
    if _openai_client is None:
        try:
            from openai import OpenAI
            _openai_client = OpenAI(api_key=OPENAI_API_KEY)
            print(f"✓ OpenAI client initialized")
        except Exception as e:
            print(f"✗ OpenAI initialization failed: {e}")
            raise
    return _openai_client


# =============================================================================
# SIMPLE CACHE
# =============================================================================
class SimpleCache:
    """Thread-safe in-memory cache with TTL."""
    
    def __init__(self, max_entries=1000, ttl_seconds=3600):
        self.max_entries = max_entries
        self.ttl_seconds = ttl_seconds
        self.cache = OrderedDict()
        self.lock = threading.RLock()
        self.hits = 0
        self.misses = 0
    
    def _make_key(self, query: str) -> str:
        return hashlib.sha256(query.lower().strip().encode()).hexdigest()[:16]
    
    def get(self, query: str):
        with self.lock:
            key = self._make_key(query)
            if key in self.cache:
                entry = self.cache[key]
                if time.time() - entry['timestamp'] <= self.ttl_seconds:
                    self.cache.move_to_end(key)
                    self.hits += 1
                    return entry['data']
                else:
                    del self.cache[key]
            self.misses += 1
            return None
    
    def set(self, query: str, data):
        with self.lock:
            key = self._make_key(query)
            self.cache[key] = {'data': data, 'timestamp': time.time()}
            self.cache.move_to_end(key)
            while len(self.cache) > self.max_entries:
                self.cache.popitem(last=False)
    
    def stats(self):
        total = self.hits + self.misses
        hit_rate = (self.hits / total * 100) if total > 0 else 0
        return {
            'entries': len(self.cache),
            'hits': self.hits,
            'misses': self.misses,
            'hit_rate': f"{hit_rate:.1f}%"
        }
    
    def clear(self):
        with self.lock:
            self.cache.clear()
            self.hits = 0
            self.misses = 0


# Initialize caches
search_cache = SimpleCache(max_entries=1000, ttl_seconds=3600)
summary_cache = SimpleCache(max_entries=500, ttl_seconds=3600)


# =============================================================================
# API KEY AUTHENTICATION
# =============================================================================
API_KEYS = {}
if API_KEY_POC:
    API_KEYS[API_KEY_POC] = 'poc'
if API_KEY_WORDPRESS:
    API_KEYS[API_KEY_WORDPRESS] = 'wordpress'


def require_api_key(f):
    """Decorator requiring valid API key in X-API-Key header."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        api_key = request.headers.get('X-API-Key')
        
        if not api_key:
            return jsonify({
                'error': 'API key required',
                'message': 'Include X-API-Key header with your request'
            }), 401
        
        if api_key not in API_KEYS:
            return jsonify({
                'error': 'Invalid API key',
                'message': 'The provided API key is not valid'
            }), 401
        
        request.client_name = API_KEYS[api_key]
        return f(*args, **kwargs)
    
    return decorated_function


def optional_api_key(f):
    """Decorator that checks API key but doesn't require it."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        api_key = request.headers.get('X-API-Key')
        
        if api_key and api_key in API_KEYS:
            request.client_name = API_KEYS[api_key]
        else:
            request.client_name = 'anonymous'
        
        return f(*args, **kwargs)
    
    return decorated_function


# =============================================================================
# ADMIN AUTHENTICATION
# =============================================================================
def check_admin_auth(username, password):
    """Verify admin credentials."""
    return username == ADMIN_USERNAME and password == ADMIN_PASSWORD


def require_admin_auth(f):
    """Decorator for HTTP Basic Auth on admin routes."""
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_admin_auth(auth.username, auth.password):
            return Response(
                'Authentication required for admin access.',
                401,
                {'WWW-Authenticate': 'Basic realm="Albert Mohler Admin"'}
            )
        return f(*args, **kwargs)
    return decorated


# =============================================================================
# RATE LIMITING
# =============================================================================
rate_limit_data = {}


def check_rate_limit(client_key, limit_per_minute, limit_per_hour):
    """Check if client has exceeded rate limits."""
    now = datetime.now()
    minute_ago = now - timedelta(minutes=1)
    hour_ago = now - timedelta(hours=1)
    
    if client_key not in rate_limit_data:
        rate_limit_data[client_key] = []
    
    # Clean old entries
    rate_limit_data[client_key] = [
        t for t in rate_limit_data[client_key] 
        if t > hour_ago
    ]
    
    requests_last_minute = sum(1 for t in rate_limit_data[client_key] if t > minute_ago)
    requests_last_hour = len(rate_limit_data[client_key])
    
    if requests_last_minute >= limit_per_minute:
        return False, 60
    
    if requests_last_hour >= limit_per_hour:
        return False, 3600
    
    rate_limit_data[client_key].append(now)
    return True, 0


def rate_limit(per_minute=30, per_hour=200):
    """Decorator to apply rate limiting."""
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            api_key = request.headers.get('X-API-Key', request.remote_addr)
            
            allowed, retry_after = check_rate_limit(
                f"{api_key}:{f.__name__}", 
                per_minute, 
                per_hour
            )
            
            if not allowed:
                return jsonify({
                    'error': 'Rate limit exceeded',
                    'retry_after': retry_after,
                    'message': f'Please wait {retry_after} seconds before trying again'
                }), 429
            
            return f(*args, **kwargs)
        return decorated_function
    return decorator


# =============================================================================
# ANALYTICS (SQLite)
# =============================================================================
ANALYTICS_DB = SERVER_DIR / "data" / "analytics.db"

# In-memory error log (keeps last 100 errors)
error_log = []
ERROR_LOG_MAX = 100


def log_error(endpoint: str, error: str, details: dict = None):
    """Log an error to the in-memory error log."""
    error_log.append({
        'timestamp': datetime.now().isoformat(),
        'endpoint': endpoint,
        'error': str(error),
        'details': details or {}
    })
    # Keep only last 100 errors
    while len(error_log) > ERROR_LOG_MAX:
        error_log.pop(0)


def init_analytics_db():
    """Initialize SQLite analytics database."""
    ANALYTICS_DB.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(str(ANALYTICS_DB))
    c = conn.cursor()

    c.execute('''
        CREATE TABLE IF NOT EXISTS searches (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            query TEXT NOT NULL,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            client TEXT,
            results_count INTEGER
        )
    ''')

    c.execute('''
        CREATE TABLE IF NOT EXISTS vector_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            count INTEGER NOT NULL,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            source TEXT
        )
    ''')

    conn.commit()
    conn.close()


# Initialize analytics database at module load
init_analytics_db()


def record_search(query, client, results_count):
    """Record a search in SQLite database."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        c = conn.cursor()
        c.execute(
            'INSERT INTO searches (query, client, results_count) VALUES (?, ?, ?)',
            (query, client, results_count)
        )
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"Analytics error: {e}")


def get_analytics(days=7):
    """Get analytics summary from SQLite."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        cutoff = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')

        c.execute('SELECT COUNT(*) as count FROM searches WHERE timestamp > ?', (cutoff,))
        total_searches = c.fetchone()['count']

        c.execute('SELECT COUNT(DISTINCT query) as count FROM searches WHERE timestamp > ?', (cutoff,))
        unique_queries = c.fetchone()['count']

        c.execute('''
            SELECT query, COUNT(*) as count
            FROM searches WHERE timestamp > ?
            GROUP BY LOWER(query) ORDER BY count DESC LIMIT 20
        ''', (cutoff,))
        top_queries = [{'query': row['query'], 'count': row['count']} for row in c.fetchall()]

        c.execute('''
            SELECT client, COUNT(*) as count
            FROM searches WHERE timestamp > ?
            GROUP BY client
        ''', (cutoff,))
        by_client = {row['client']: row['count'] for row in c.fetchall()}

        c.execute('''
            SELECT DATE(timestamp) as date, COUNT(*) as count
            FROM searches WHERE timestamp > ?
            GROUP BY DATE(timestamp) ORDER BY date DESC
        ''', (cutoff,))
        by_day = [{'date': row['date'], 'count': row['count']} for row in c.fetchall()]

        conn.close()

        return {
            'period': f'{days} days',
            'total_searches': total_searches,
            'unique_queries': unique_queries,
            'top_queries': top_queries,
            'searches_by_client': by_client,
            'searches_by_day': by_day
        }
    except Exception as e:
        return {'error': str(e)}


def get_recent_searches(limit=20):
    """Get recent searches from SQLite."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        c.execute('''
            SELECT query, timestamp, client, results_count
            FROM searches ORDER BY timestamp DESC LIMIT ?
        ''', (limit,))

        searches = [{
            'query': row['query'],
            'timestamp': row['timestamp'],
            'client': row['client'],
            'results_count': row['results_count']
        } for row in c.fetchall()]

        conn.close()
        return searches
    except Exception as e:
        print(f"Error getting recent searches: {e}")
        return []


def get_zero_result_queries(days=30, limit=20):
    """Get queries that returned zero results from SQLite."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        cutoff = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')

        c.execute('''
            SELECT query, COUNT(*) as count, MAX(timestamp) as last_searched
            FROM searches
            WHERE timestamp > ? AND results_count = 0
            GROUP BY LOWER(query)
            ORDER BY count DESC
            LIMIT ?
        ''', (cutoff, limit))

        queries = [{
            'query': row['query'],
            'count': row['count'],
            'last_searched': row['last_searched']
        } for row in c.fetchall()]

        conn.close()
        return queries
    except Exception as e:
        print(f"Error getting zero result queries: {e}")
        return []


def get_search_trends(days=30):
    """Get daily search counts for trend chart from SQLite."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        cutoff = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')

        c.execute('''
            SELECT DATE(timestamp) as date, COUNT(*) as count
            FROM searches
            WHERE timestamp > ?
            GROUP BY DATE(timestamp)
            ORDER BY date ASC
        ''', (cutoff,))

        trends = [{'date': row['date'], 'count': row['count']} for row in c.fetchall()]

        conn.close()
        return trends
    except Exception as e:
        print(f"Error getting search trends: {e}")
        return []


def get_hourly_distribution(days=7):
    """Get search distribution by hour of day from SQLite."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        cutoff = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')

        c.execute('''
            SELECT strftime('%H', timestamp) as hour, COUNT(*) as count
            FROM searches
            WHERE timestamp > ?
            GROUP BY strftime('%H', timestamp)
            ORDER BY hour ASC
        ''', (cutoff,))

        distribution = {row['hour']: row['count'] for row in c.fetchall()}

        conn.close()
        return distribution
    except Exception as e:
        print(f"Error getting hourly distribution: {e}")
        return {}


# =============================================================================
# PIPELINE UPDATES (GitHub Actions + Vector Snapshots)
# =============================================================================
import requests
from datetime import timezone

GITHUB_REPO = "pastormiles/mohler"
GITHUB_API_CACHE_TTL = 300  # 5 minutes

_github_cache = {'data': None, 'timestamp': 0}


def fetch_github_workflow_runs(limit=5):
    """Fetch recent GitHub Actions workflow runs with caching."""
    global _github_cache

    now = time.time()

    # Return cached data if fresh
    if _github_cache['data'] and (now - _github_cache['timestamp']) < GITHUB_API_CACHE_TTL:
        return _github_cache['data']

    try:
        url = f"https://api.github.com/repos/{GITHUB_REPO}/actions/runs"
        headers = {
            'Accept': 'application/vnd.github.v3+json',
            'User-Agent': 'AlbertMohler-Admin-Dashboard'
        }

        response = requests.get(url, headers=headers, params={'per_page': limit}, timeout=10)

        if response.status_code == 404:
            return {'error': 'Repository not found or not public', 'runs': []}

        if response.status_code == 403:
            # Rate limited - return cached data if available
            if _github_cache['data']:
                _github_cache['data']['error'] = 'GitHub API rate limit exceeded (using cached data)'
                return _github_cache['data']
            return {'error': 'GitHub API rate limit exceeded', 'runs': []}

        response.raise_for_status()
        data = response.json()

        runs = []
        for run in data.get('workflow_runs', [])[:limit]:
            # Calculate duration
            created = datetime.fromisoformat(run['created_at'].replace('Z', '+00:00'))
            updated = datetime.fromisoformat(run['updated_at'].replace('Z', '+00:00'))
            duration_seconds = int((updated - created).total_seconds())

            runs.append({
                'id': run['id'],
                'name': run['name'],
                'status': run['status'],
                'conclusion': run['conclusion'],
                'created_at': run['created_at'],
                'updated_at': run['updated_at'],
                'html_url': run['html_url'],
                'duration_seconds': duration_seconds,
                'duration_text': format_duration(duration_seconds)
            })

        result = {
            'runs': runs,
            'fetched_at': datetime.utcnow().isoformat(),
            'error': None
        }

        # Update cache
        _github_cache = {'data': result, 'timestamp': now}

        return result

    except requests.RequestException as e:
        # Return cached data if available
        if _github_cache['data']:
            _github_cache['data']['error'] = f'GitHub API error (using cached data): {str(e)}'
            return _github_cache['data']
        return {'error': str(e), 'runs': []}


def format_duration(seconds):
    """Format duration in human-readable form."""
    if seconds < 60:
        return f"{seconds}s"
    elif seconds < 3600:
        minutes = seconds // 60
        secs = seconds % 60
        return f"{minutes}m {secs}s"
    else:
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        return f"{hours}h {minutes}m"


def record_vector_snapshot(count, source="dashboard_view"):
    """Record a vector count snapshot in SQLite."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        c = conn.cursor()
        c.execute(
            'INSERT INTO vector_snapshots (count, source) VALUES (?, ?)',
            (count, source)
        )
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"Error recording vector snapshot: {e}")


def record_vector_snapshot_if_needed(count):
    """Record vector snapshot only if last one was > 1 hour ago."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        c = conn.cursor()
        hour_ago = (datetime.now() - timedelta(hours=1)).strftime('%Y-%m-%d %H:%M:%S')

        c.execute('SELECT COUNT(*) FROM vector_snapshots WHERE timestamp > ?', (hour_ago,))
        recent_count = c.fetchone()[0]

        if recent_count == 0:
            c.execute(
                'INSERT INTO vector_snapshots (count, source) VALUES (?, ?)',
                (count, "dashboard_view")
            )
            conn.commit()

        conn.close()
    except Exception as e:
        print(f"Error checking/recording snapshot: {e}")


def get_vector_history(days=7):
    """Get vector count history for trend calculation."""
    try:
        conn = sqlite3.connect(str(ANALYTICS_DB))
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        cutoff = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')

        c.execute('''
            SELECT count, timestamp, source
            FROM vector_snapshots
            WHERE timestamp > ?
            ORDER BY timestamp DESC
            LIMIT 100
        ''', (cutoff,))

        snapshots = [{
            'count': row['count'],
            'timestamp': row['timestamp'],
            'source': row['source']
        } for row in c.fetchall()]

        conn.close()
        return snapshots
    except Exception as e:
        print(f"Error getting vector history: {e}")
        return []


def calculate_vector_trend(snapshots, current_count=None):
    """Calculate vector count trend from snapshots."""
    if not snapshots and current_count is None:
        return {'current': 0, 'change_7d': 0, 'change_text': 'No data'}

    current = current_count if current_count is not None else (snapshots[0]['count'] if snapshots else 0)

    # Find snapshot from ~7 days ago
    week_ago = datetime.utcnow() - timedelta(days=7)
    week_ago_count = current

    for snap in snapshots:
        if snap['timestamp']:
            ts_str = snap['timestamp']
            if ts_str.endswith('Z'):
                ts_str = ts_str[:-1] + '+00:00'
            elif '+' not in ts_str and '-' not in ts_str[-6:]:
                ts_str = ts_str + '+00:00'
            try:
                ts = datetime.fromisoformat(ts_str)
                if ts.replace(tzinfo=None) <= week_ago:
                    week_ago_count = snap['count']
                    break
            except ValueError:
                continue

    change = current - week_ago_count
    change_text = f"+{change}" if change >= 0 else str(change)

    return {
        'current': current,
        'change_7d': change,
        'change_text': f"{current:,} vectors ({change_text} this week)"
    }


def get_pipeline_health_summary(workflow_runs):
    """Calculate pipeline health summary from workflow runs."""
    if not workflow_runs:
        return {
            'status': 'unknown',
            'status_text': 'No workflow data',
            'last_success': None,
            'days_since_success': None
        }

    # Find last successful run
    last_success = None
    for run in workflow_runs:
        if run.get('conclusion') == 'success':
            last_success = run
            break

    # Determine overall status
    latest = workflow_runs[0]
    if latest.get('status') == 'in_progress':
        status = 'running'
        status_text = 'Pipeline running'
    elif latest.get('conclusion') == 'success':
        status = 'healthy'
        status_text = 'Pipeline healthy'
    elif latest.get('conclusion') == 'failure':
        status = 'failed'
        status_text = 'Last run failed'
    else:
        status = 'unknown'
        status_text = f"Status: {latest.get('conclusion') or latest.get('status')}"

    # Calculate days since last success
    days_since_success = None
    if last_success:
        success_time_str = last_success['created_at'].replace('Z', '+00:00')
        success_time = datetime.fromisoformat(success_time_str)
        days_since_success = (datetime.now(timezone.utc) - success_time).days

    return {
        'status': status,
        'status_text': status_text,
        'last_success': last_success['created_at'] if last_success else None,
        'days_since_success': days_since_success
    }


# =============================================================================
# API ROUTES
# =============================================================================

@api_v1.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint."""
    try:
        # Test Pinecone connection
        index = get_pinecone_index()
        stats = index.describe_index_stats()
        pinecone_status = 'connected'
        vector_count = stats.get('namespaces', {}).get(PINECONE_NAMESPACE, {}).get('vector_count', 0)
    except Exception as e:
        pinecone_status = f'error: {str(e)}'
        vector_count = 0
    
    return jsonify({
        'status': 'healthy',
        'version': 'youtube-search-v1',
        'channel': CHANNEL_DISPLAY_NAME,
        'pinecone_index': PINECONE_INDEX,
        'pinecone_namespace': PINECONE_NAMESPACE,
        'pinecone_status': pinecone_status,
        'vector_count': vector_count,
        'cache': search_cache.stats()
    })


@api_v1.route('/search', methods=['POST'])
@optional_api_key
@rate_limit(per_minute=30, per_hour=200)
def search():
    """Search YouTube transcripts."""
    try:
        data = request.get_json()
        query = data.get('query', '')
        top_k = min(data.get('top_k', 15), 50)
        
        if not query:
            return jsonify({'error': 'Query is required'}), 400
        
        # Check cache
        cached = search_cache.get(query)
        if cached:
            return jsonify({
                'query': query,
                'results': cached,
                'count': len(cached),
                'cached': True
            })
        
        # Generate embedding
        client = get_openai_client()
        response = client.embeddings.create(
            model=EMBEDDING_MODEL,
            input=query
        )
        query_embedding = response.data[0].embedding
        
        # Search Pinecone
        index = get_pinecone_index()
        results = index.query(
            vector=query_embedding,
            top_k=top_k,
            include_metadata=True,
            namespace=PINECONE_NAMESPACE
        )
        
        # Format results
        formatted_results = []
        seen_videos = set()
        
        for match in results['matches']:
            metadata = match['metadata']
            video_id = metadata.get('video_id', '')
            
            formatted_results.append({
                'score': match['score'],
                'chunk_id': match['id'],
                'video_id': video_id,
                'video_title': metadata.get('video_title', ''),
                'text': metadata.get('text', ''),
                'start_time': metadata.get('start_time', 0),
                'end_time': metadata.get('end_time', 0),
                'start_timestamp': metadata.get('start_timestamp', '0:00'),
                'end_timestamp': metadata.get('end_timestamp', '0:00'),
                'thumbnail_url': metadata.get('thumbnail_url', ''),
                'youtube_url': metadata.get('youtube_url', ''),
                'is_new_video': video_id not in seen_videos
            })
            seen_videos.add(video_id)
        
        # Cache and record
        search_cache.set(query, formatted_results)
        record_search(query, getattr(request, 'client_name', 'anonymous'), len(formatted_results))
        
        return jsonify({
            'query': query,
            'results': formatted_results,
            'count': len(formatted_results),
            'unique_videos': len(seen_videos),
            'cached': False
        })
        
    except Exception as e:
        print(f"Search error: {str(e)}")
        log_error('search', str(e), {'query': query if 'query' in dir() else 'unknown'})
        return jsonify({'error': str(e)}), 500


@api_v1.route('/summarize', methods=['POST'])
@optional_api_key
@rate_limit(per_minute=10, per_hour=50)
def summarize_results():
    """Generate AI summary of search results."""
    try:
        data = request.get_json()
        query = data.get('query', '')
        results = data.get('results', [])
        
        if not query:
            return jsonify({'error': 'Query is required'}), 400
        
        if not results:
            return jsonify({'error': 'No results to summarize'}), 400
        
        # Check cache
        cache_key = f"{query}:{len(results)}"
        cached = summary_cache.get(cache_key)
        if cached:
            cached['cached'] = True
            return jsonify(cached)
        
        # Use top 5 results
        top_results = results[:5]
        
        context_parts = []
        for i, result in enumerate(top_results, 1):
            context_parts.append(
                f"[Video {i}: {result.get('video_title', 'Unknown')} at {result.get('start_timestamp', '0:00')}]\n"
                f"Transcript: {result.get('text', '')[:600]}"
            )
        
        context = "\n\n".join(context_parts)
        
        # Generate summary
        client = get_openai_client()
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a helpful assistant summarizing content from "
                        "Albert Mohler's YouTube videos. Synthesize the provided "
                        "transcript excerpts into a clear, informative answer of 150-200 words. "
                        "Mention which videos discuss the topic. Be accurate and faithful to "
                        "what was actually said. Start directly with the substance - never begin "
                        "with phrases like 'In recent discussions' or 'In his videos'."
                    )
                },
                {
                    "role": "user",
                    "content": f"Question: {query}\n\nVideo transcript excerpts:\n\n{context}"
                }
            ],
            max_tokens=400,
            temperature=0.3
        )
        
        summary = response.choices[0].message.content
        
        # Get all sources with details
        sources = []
        seen_videos = set()
        for r in top_results:
            video_id = r.get('video_id', '')
            if video_id and video_id not in seen_videos:
                sources.append({
                    'title': r.get('video_title', ''),
                    'timestamp': r.get('start_timestamp', '0:00'),
                    'url': r.get('youtube_url', '')
                })
                seen_videos.add(video_id)

        result_data = {
            'query': query,
            'summary': summary,
            'sources': sources,
            'sources_count': len(top_results),
            'cached': False
        }
        
        summary_cache.set(cache_key, result_data)
        
        return jsonify(result_data)
        
    except Exception as e:
        print(f"Summarize error: {str(e)}")
        log_error('summarize', str(e), {'query': query if 'query' in dir() else 'unknown'})
        return jsonify({'error': str(e)}), 500


@api_v1.route('/stats', methods=['GET'])
@optional_api_key
def get_stats():
    """Get index statistics."""
    try:
        index = get_pinecone_index()
        stats = index.describe_index_stats()
        namespaces = stats.get('namespaces', {})
        youtube_stats = namespaces.get(PINECONE_NAMESPACE, {})
        
        return jsonify({
            'namespace': PINECONE_NAMESPACE,
            'vector_count': youtube_stats.get('vector_count', 0),
            'total_index_vectors': stats.get('total_vector_count', 0)
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@api_v1.route('/admin/dashboard-data', methods=['GET'])
@require_admin_auth
def admin_dashboard_data():
    """Get dashboard data."""
    try:
        # Pinecone stats
        try:
            index = get_pinecone_index()
            stats = index.describe_index_stats()
            pinecone_status = 'connected'
            total_vectors = stats.get('namespaces', {}).get(PINECONE_NAMESPACE, {}).get('vector_count', 0)

            # Record vector snapshot (throttled to 1 per hour)
            record_vector_snapshot_if_needed(total_vectors)
        except Exception as e:
            pinecone_status = f'error: {str(e)}'
            total_vectors = 0

        # OpenAI status
        try:
            client = get_openai_client()
            openai_status = 'connected'
        except Exception as e:
            openai_status = f'error: {str(e)}'

        # Fetch GitHub workflow runs
        github_data = fetch_github_workflow_runs(limit=5)

        # Get vector history and calculate trend
        vector_history = get_vector_history(days=7)
        vector_trend = calculate_vector_trend(vector_history, current_count=total_vectors)

        # Calculate pipeline health summary
        pipeline_health = get_pipeline_health_summary(github_data.get('runs', []))

        return jsonify({
            'system': {
                'api_version': 'v1',
                'channel': CHANNEL_DISPLAY_NAME,
                'pinecone_status': pinecone_status,
                'openai_status': openai_status,
                'total_vectors': total_vectors,
            },
            'updates': {
                'github_runs': github_data.get('runs', []),
                'github_error': github_data.get('error'),
                'github_fetched_at': github_data.get('fetched_at'),
                'vector_trend': vector_trend,
                'vector_history': vector_history[:10],
                'pipeline_health': pipeline_health
            },
            'analytics_1d': get_analytics(1),
            'analytics_7d': get_analytics(7),
            'analytics_30d': get_analytics(30),
            'recent_searches': get_recent_searches(20),
            'zero_result_queries': get_zero_result_queries(30, 15),
            'search_trends': get_search_trends(30),
            'hourly_distribution': get_hourly_distribution(7),
            'error_log': error_log[-20:],  # Last 20 errors
            'cache': {
                'search': search_cache.stats(),
                'summary': summary_cache.stats()
            },
            'timestamp': datetime.now().isoformat()
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@api_v1.route('/admin/debug-search', methods=['POST'])
@require_admin_auth
def admin_debug_search():
    """Debug search - returns raw Pinecone results with scores."""
    try:
        data = request.get_json()
        query = data.get('query', '')
        top_k = min(data.get('top_k', 10), 20)

        if not query:
            return jsonify({'error': 'Query is required'}), 400

        # Generate embedding
        client = get_openai_client()
        response = client.embeddings.create(
            model=EMBEDDING_MODEL,
            input=query
        )
        query_embedding = response.data[0].embedding

        # Search Pinecone
        index = get_pinecone_index()
        results = index.query(
            vector=query_embedding,
            top_k=top_k,
            include_metadata=True,
            namespace=PINECONE_NAMESPACE
        )

        # Return raw results with all metadata
        raw_results = []
        for match in results['matches']:
            raw_results.append({
                'id': match['id'],
                'score': round(match['score'], 4),
                'metadata': match.get('metadata', {})
            })

        return jsonify({
            'query': query,
            'embedding_model': EMBEDDING_MODEL,
            'embedding_dimensions': len(query_embedding),
            'results': raw_results,
            'count': len(raw_results)
        })

    except Exception as e:
        log_error('admin/debug-search', str(e), {'query': query})
        return jsonify({'error': str(e)}), 500


@api_v1.route('/admin/sample-videos', methods=['GET'])
@require_admin_auth
def admin_sample_videos():
    """Get a sample of indexed videos."""
    try:
        index = get_pinecone_index()

        # Query with a generic vector to get random samples
        # Use a zero vector to get diverse results
        sample_vector = [0.0] * 1536

        results = index.query(
            vector=sample_vector,
            top_k=100,
            include_metadata=True,
            namespace=PINECONE_NAMESPACE
        )

        # Extract unique videos
        videos = {}
        for match in results['matches']:
            meta = match.get('metadata', {})
            video_id = meta.get('video_id', '')
            if video_id and video_id not in videos:
                videos[video_id] = {
                    'video_id': video_id,
                    'title': meta.get('video_title', ''),
                    'thumbnail_url': meta.get('thumbnail_url', ''),
                    'youtube_url': f"https://www.youtube.com/watch?v={video_id}"
                }

        return jsonify({
            'videos': list(videos.values())[:50],
            'count': len(videos),
            'note': 'Sample of indexed videos (not complete list)'
        })

    except Exception as e:
        log_error('admin/sample-videos', str(e))
        return jsonify({'error': str(e)}), 500


@api_v1.route('/admin/clear-cache', methods=['POST'])
@require_admin_auth
def admin_clear_cache():
    """Clear all caches."""
    try:
        search_cache.clear()
        summary_cache.clear()
        return jsonify({
            'status': 'success',
            'message': 'All caches cleared'
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@api_v1.route('/admin/health-check', methods=['GET'])
@require_admin_auth
def admin_health_check():
    """Detailed health check for all services."""
    health = {
        'timestamp': datetime.now().isoformat(),
        'services': {}
    }

    # Check Pinecone
    try:
        start = time.time()
        index = get_pinecone_index()
        stats = index.describe_index_stats()
        latency = round((time.time() - start) * 1000, 2)
        health['services']['pinecone'] = {
            'status': 'healthy',
            'latency_ms': latency,
            'vectors': stats.get('namespaces', {}).get(PINECONE_NAMESPACE, {}).get('vector_count', 0)
        }
    except Exception as e:
        health['services']['pinecone'] = {'status': 'error', 'error': str(e)}

    # Check OpenAI
    try:
        start = time.time()
        client = get_openai_client()
        # Quick test embedding
        response = client.embeddings.create(
            model=EMBEDDING_MODEL,
            input="health check"
        )
        latency = round((time.time() - start) * 1000, 2)
        health['services']['openai'] = {
            'status': 'healthy',
            'latency_ms': latency,
            'model': EMBEDDING_MODEL
        }
    except Exception as e:
        health['services']['openai'] = {'status': 'error', 'error': str(e)}

    # Check Firestore
    try:
        start = time.time()
        db = get_firestore_client()
        # Quick read test
        db.collection('searches').limit(1).get()
        latency = round((time.time() - start) * 1000, 2)
        health['services']['firestore'] = {
            'status': 'healthy',
            'latency_ms': latency
        }
    except Exception as e:
        health['services']['firestore'] = {'status': 'error', 'error': str(e)}

    # Overall status
    all_healthy = all(s.get('status') == 'healthy' for s in health['services'].values())
    health['overall'] = 'healthy' if all_healthy else 'degraded'

    return jsonify(health)


# Register blueprint
app.register_blueprint(api_v1)


# =============================================================================
# ADMIN DASHBOARD
# =============================================================================
ADMIN_HTML = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Albert Mohler Search - Admin</title>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;600;700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Lato', -apple-system, BlinkMacSystemFont, sans-serif; background: #f7f7f7; color: #1a202c; }
        .header { background: linear-gradient(135deg, #1e3a5f 0%, #2d5a87 100%); color: white; padding: 20px 30px; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px; }
        .header h1 { font-size: 1.5rem; font-weight: 700; }
        .header-subtitle { font-size: 0.85rem; opacity: 0.9; }
        .container { max-width: 1400px; margin: 0 auto; padding: 20px; }
        .tabs { display: flex; gap: 10px; margin-bottom: 20px; flex-wrap: wrap; }
        .tab { padding: 10px 20px; background: white; border: 2px solid #e2e8f0; border-radius: 8px; cursor: pointer; font-weight: 600; transition: all 0.2s; }
        .tab:hover { border-color: #1e3a5f; }
        .tab.active { background: #1e3a5f; color: white; border-color: #1e3a5f; }
        .tab-content { display: none; }
        .tab-content.active { display: block; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px; margin-bottom: 20px; }
        .grid-2 { display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 20px; margin-bottom: 20px; }
        .card { background: white; border-radius: 12px; padding: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); border: 1px solid #e2e8f0; }
        .card-title { font-size: 0.8rem; font-weight: 700; color: #4a5568; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 15px; display: flex; justify-content: space-between; align-items: center; }
        .stat-value { font-size: 2.5rem; font-weight: 700; color: #1e3a5f; }
        .stat-label { color: #4a5568; font-size: 0.85rem; }
        .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 0.8rem; font-weight: 600; }
        .status-healthy { background: #d4edda; color: #155724; }
        .status-error { background: #f8d7da; color: #721c24; }
        .status-warning { background: #fff3cd; color: #856404; }
        .status-success { background: #d4edda; color: #155724; }
        .status-failure { background: #f8d7da; color: #721c24; }
        .status-in_progress { background: #fff3cd; color: #856404; }
        .status-pending { background: #e9ecef; color: #495057; }
        .status-cancelled { background: #e9ecef; color: #6c757d; }
        .status-running { background: #cce5ff; color: #004085; }
        .status-unknown { background: #e9ecef; color: #495057; }
        table { width: 100%; border-collapse: collapse; }
        th { text-align: left; padding: 12px 10px; border-bottom: 2px solid #e2e8f0; font-weight: 600; color: #4a5568; font-size: 0.85rem; text-transform: uppercase; }
        td { text-align: left; padding: 12px 10px; border-bottom: 1px solid #eee; font-size: 0.9rem; }
        tr:hover { background: #f7f7f7; }
        .btn { background: #1e3a5f; border: none; color: white; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-weight: 600; font-size: 0.85rem; }
        .btn:hover { background: #2d5a87; }
        .btn-secondary { background: white; color: #1e3a5f; border: 2px solid #1e3a5f; }
        .btn-secondary:hover { background: #f0f4f8; }
        .btn-sm { padding: 5px 12px; font-size: 0.8rem; }
        .refresh-btn { background: white; border: none; color: #1e3a5f; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-weight: 600; }
        .refresh-btn:hover { background: rgba(255,255,255,0.9); }
        .back-link { color: white; text-decoration: none; margin-right: 15px; opacity: 0.9; }
        .back-link:hover { opacity: 1; }
        .metric-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
        .metric-row:last-child { border-bottom: none; }
        .metric-label { color: #4a5568; }
        .metric-value { font-weight: 600; color: #1a202c; }
        .metric-value.highlight { color: #1e3a5f; }
        .input-group { display: flex; gap: 10px; margin-bottom: 15px; }
        .input-group input { flex: 1; padding: 10px 15px; border: 2px solid #e2e8f0; border-radius: 8px; font-size: 0.95rem; }
        .input-group input:focus { outline: none; border-color: #1e3a5f; }
        .debug-result { background: #f7f7f7; border-radius: 8px; padding: 15px; margin-top: 15px; font-family: monospace; font-size: 0.85rem; max-height: 400px; overflow-y: auto; }
        .error-item { background: #fef2f2; border-left: 4px solid #dc3545; padding: 12px; margin-bottom: 10px; border-radius: 0 8px 8px 0; }
        .error-time { font-size: 0.8rem; color: #666; }
        .error-endpoint { font-weight: 600; color: #dc3545; }
        .video-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 15px; }
        .video-card { background: #f7f7f7; border-radius: 8px; overflow: hidden; }
        .video-card img { width: 100%; aspect-ratio: 16/9; object-fit: cover; }
        .video-card-info { padding: 10px; font-size: 0.85rem; }
        .video-card-title { font-weight: 600; color: #1a202c; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
        .chart-container { position: relative; height: 250px; }
        .client-badge { display: inline-block; padding: 4px 10px; border-radius: 4px; font-size: 0.75rem; font-weight: 500; }
        .client-anonymous { background: #e9ecef; color: #495057; }
        .client-wordpress { background: #ffe0e6; color: #9d174d; }
        .client-poc { background: #dbeafe; color: #1e40af; }
        /* Pipeline Updates section */
        .updates-summary { display: flex; align-items: center; gap: 15px; margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #eee; }
        .updates-summary .summary-text { flex: 1; }
        .updates-summary .summary-text h3 { font-size: 1rem; color: #333; margin-bottom: 4px; }
        .updates-summary .summary-text p { font-size: 0.85rem; color: #666; margin: 0; }
        .workflow-run { display: flex; align-items: center; padding: 10px 0; border-bottom: 1px solid #f0f0f0; gap: 12px; }
        .workflow-run:last-child { border-bottom: none; }
        .workflow-run .run-status { min-width: 70px; }
        .workflow-run .run-info { flex: 1; }
        .workflow-run .run-name { font-weight: 500; color: #333; font-size: 0.9rem; }
        .workflow-run .run-time { font-size: 0.8rem; color: #888; }
        .workflow-run .run-duration { font-size: 0.8rem; color: #666; min-width: 60px; text-align: right; }
        .workflow-run a { color: #1e3a5f; text-decoration: none; font-size: 0.8rem; }
        .workflow-run a:hover { text-decoration: underline; }
        .vector-trend { display: flex; align-items: baseline; gap: 10px; flex-wrap: wrap; }
        .vector-trend .trend-value { font-size: 1.5rem; font-weight: 700; color: #1e3a5f; }
        .vector-trend .trend-change { font-size: 0.9rem; color: #28a745; }
        .vector-trend .trend-change.negative { color: #dc3545; }
        .section-divider { margin: 15px 0; padding-top: 15px; border-top: 1px solid #eee; }
        @media (max-width: 768px) {
            .grid-2 { grid-template-columns: 1fr; }
        }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1>Albert Mohler Search Dashboard</h1>
            <div class="header-subtitle">am.nomion.ai Admin</div>
        </div>
        <div>
            <a href="/" class="back-link">← Back to Search</a>
            <button class="refresh-btn" onclick="loadDashboard()">↻ Refresh</button>
        </div>
    </div>
    <div class="container">
        <div class="tabs">
            <div class="tab active" onclick="showTab('overview')">Overview</div>
            <div class="tab" onclick="showTab('pipeline')">Pipeline</div>
            <div class="tab" onclick="showTab('analytics')">Analytics</div>
            <div class="tab" onclick="showTab('content')">Content Gaps</div>
            <div class="tab" onclick="showTab('tools')">Tools</div>
            <div class="tab" onclick="showTab('errors')">Errors</div>
            <div class="tab" onclick="showTab('videos')">Videos</div>
        </div>
        <div id="overview" class="tab-content active"></div>
        <div id="pipeline" class="tab-content"></div>
        <div id="analytics" class="tab-content"></div>
        <div id="content" class="tab-content"></div>
        <div id="tools" class="tab-content"></div>
        <div id="errors" class="tab-content"></div>
        <div id="videos" class="tab-content"></div>
    </div>
    <script>
        let dashboardData = null;
        let trendsChart = null;

        function showTab(tabId) {
            document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
            document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
            document.querySelector(`.tab[onclick="showTab('${tabId}')"]`).classList.add('active');
            document.getElementById(tabId).classList.add('active');
            if (tabId === 'analytics' && dashboardData) renderAnalytics();
            if (tabId === 'videos') loadVideos();
        }

        async function loadDashboard() {
            try {
                const res = await fetch('/api/v1/admin/dashboard-data');
                dashboardData = await res.json();
                renderOverview();
                renderPipeline();
                renderContent();
                renderTools();
                renderErrors();
            } catch (e) {
                document.getElementById('overview').innerHTML = `<div class="card">Error: ${e.message}</div>`;
            }
        }

        function formatDate(dateStr) {
            const d = new Date(dateStr);
            return d.toLocaleDateString('en-US', { month: 'numeric', day: 'numeric', year: 'numeric' }) + ', ' +
                   d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
        }

        function getClientBadgeClass(client) {
            if (client === 'wordpress') return 'client-wordpress';
            if (client === 'poc') return 'client-poc';
            return 'client-anonymous';
        }

        function getStatusBadgeClass(status, conclusion) {
            if (status === 'in_progress') return 'status-in_progress';
            if (status === 'queued') return 'status-pending';
            if (conclusion === 'success') return 'status-success';
            if (conclusion === 'failure') return 'status-failure';
            if (conclusion === 'cancelled') return 'status-cancelled';
            return 'status-pending';
        }

        function getStatusText(status, conclusion) {
            if (status === 'in_progress') return 'Running';
            if (status === 'queued') return 'Queued';
            if (conclusion === 'success') return 'Success';
            if (conclusion === 'failure') return 'Failed';
            if (conclusion === 'cancelled') return 'Cancelled';
            return status || 'Pending';
        }

        function formatRelativeTime(dateStr) {
            const now = new Date();
            const date = new Date(dateStr);
            const diffMs = now - date;
            const diffMins = Math.floor(diffMs / 60000);
            const diffHours = Math.floor(diffMs / 3600000);
            const diffDays = Math.floor(diffMs / 86400000);

            if (diffMins < 1) return 'just now';
            if (diffMins < 60) return diffMins + 'm ago';
            if (diffHours < 24) return diffHours + 'h ago';
            if (diffDays === 1) return 'yesterday';
            return diffDays + ' days ago';
        }

        function getPipelineStatusClass(status) {
            if (status === 'healthy') return 'status-healthy';
            if (status === 'running') return 'status-running';
            if (status === 'failed') return 'status-error';
            return 'status-unknown';
        }

        function renderOverview() {
            const sys = dashboardData.system;
            const a1d = dashboardData.analytics_1d || {};
            const a7d = dashboardData.analytics_7d || {};
            const a30d = dashboardData.analytics_30d || {};
            const recent = dashboardData.recent_searches || [];

            document.getElementById('overview').innerHTML = `
                <div class="grid">
                    <div class="card">
                        <div class="card-title">System Status</div>
                        <div style="margin-bottom: 15px;">
                            <span class="status-badge ${sys.pinecone_status === 'connected' && sys.openai_status === 'connected' ? 'status-healthy' : 'status-error'}">
                                ${sys.pinecone_status === 'connected' && sys.openai_status === 'connected' ? '● All Systems Healthy' : '● Issues Detected'}
                            </span>
                        </div>
                        <div class="metric-row">
                            <span class="metric-label">Pinecone</span>
                            <span class="metric-value">${sys.pinecone_status}</span>
                        </div>
                        <div class="metric-row">
                            <span class="metric-label">OpenAI</span>
                            <span class="metric-value">${sys.openai_status}</span>
                        </div>
                        <div class="metric-row">
                            <span class="metric-label">Total Vectors</span>
                            <span class="metric-value highlight">${sys.total_vectors?.toLocaleString() || 0}</span>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-title">Today</div>
                        <div class="stat-value">${a1d.total_searches || 0}</div>
                        <div class="stat-label">searches today</div>
                    </div>
                    <div class="card">
                        <div class="card-title">Last 7 Days</div>
                        <div class="stat-value">${a7d.total_searches || 0}</div>
                        <div class="stat-label">total searches</div>
                        <div style="margin-top: 8px; color: #4a5568; font-size: 0.9rem;">${a7d.unique_queries || 0} unique queries</div>
                    </div>
                    <div class="card">
                        <div class="card-title">Last 30 Days</div>
                        <div class="stat-value">${a30d.total_searches || 0}</div>
                        <div class="stat-label">total searches</div>
                        <div style="margin-top: 8px; color: #4a5568; font-size: 0.9rem;">${a30d.unique_queries || 0} unique queries</div>
                    </div>
                </div>
                <div class="grid-2">
                    <div class="card">
                        <div class="card-title">Cache Performance
                            <button class="btn btn-sm btn-secondary" onclick="clearCache()">Clear Cache</button>
                        </div>
                        <div class="metric-row">
                            <span class="metric-label">Search Cache</span>
                            <span class="metric-value">${dashboardData.cache?.search?.hit_rate || '0%'} hit rate (${dashboardData.cache?.search?.entries || 0} entries)</span>
                        </div>
                        <div class="metric-row">
                            <span class="metric-label">Summary Cache</span>
                            <span class="metric-value">${dashboardData.cache?.summary?.hit_rate || '0%'} hit rate (${dashboardData.cache?.summary?.entries || 0} entries)</span>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-title">Usage by Client</div>
                        ${Object.entries(a7d.searches_by_client || {}).map(([client, count]) => `
                            <div class="metric-row">
                                <span class="metric-label">${client}</span>
                                <span class="metric-value">${count}</span>
                            </div>
                        `).join('') || '<p style="color: #888;">No data yet</p>'}
                    </div>
                </div>
                <div class="grid-2">
                    <div class="card">
                        <div class="card-title">Top Queries (7 Days)</div>
                        <table>
                            <thead><tr><th>#</th><th>Query</th><th>Count</th></tr></thead>
                            <tbody>
                                ${(a7d.top_queries || []).slice(0, 10).map((q, i) => `
                                    <tr>
                                        <td>${i + 1}</td>
                                        <td>${escapeHtml(q.query)}</td>
                                        <td>${q.count}</td>
                                    </tr>
                                `).join('') || '<tr><td colspan="3" style="color: #888;">No queries yet</td></tr>'}
                            </tbody>
                        </table>
                    </div>
                    <div class="card">
                        <div class="card-title">Recent Searches</div>
                        <table>
                            <thead><tr><th>Time</th><th>Query</th><th>Results</th></tr></thead>
                            <tbody>
                                ${recent.slice(0, 10).map(s => `
                                    <tr>
                                        <td>${formatDate(s.timestamp)}</td>
                                        <td>${escapeHtml(s.query)}</td>
                                        <td>${s.results_count}</td>
                                    </tr>
                                `).join('') || '<tr><td colspan="3" style="color: #888;">No searches yet</td></tr>'}
                            </tbody>
                        </table>
                    </div>
                </div>
            `;
        }

        function renderPipeline() {
            const updates = dashboardData.updates || {};
            const githubRuns = updates.github_runs || [];
            const vectorTrend = updates.vector_trend || {};
            const pipelineHealth = updates.pipeline_health || {};
            const githubError = updates.github_error;

            document.getElementById('pipeline').innerHTML = `
                <div class="card" style="margin-bottom: 20px;">
                    <div class="card-title">Pipeline Health</div>
                    <div class="updates-summary">
                        <span class="status-badge ${getPipelineStatusClass(pipelineHealth.status)}" style="font-size: 0.85rem; padding: 6px 14px;">
                            ${pipelineHealth.status === 'healthy' ? '✓' : pipelineHealth.status === 'running' ? '↻' : pipelineHealth.status === 'failed' ? '✗' : '?'} ${pipelineHealth.status_text || 'Unknown'}
                        </span>
                        <div class="summary-text">
                            ${pipelineHealth.days_since_success !== null && pipelineHealth.days_since_success !== undefined
                                ? '<p>Last successful run: ' + (pipelineHealth.days_since_success === 0 ? 'today' : pipelineHealth.days_since_success + ' day' + (pipelineHealth.days_since_success === 1 ? '' : 's') + ' ago') + '</p>'
                                : '<p>No successful runs recorded</p>'
                            }
                        </div>
                    </div>
                    <div class="section-divider">
                        <div class="card-title" style="margin-bottom: 8px;">Vector Count</div>
                        <div class="vector-trend">
                            <span class="trend-value">${vectorTrend.current?.toLocaleString() || '0'}</span>
                            <span class="trend-change ${vectorTrend.change_7d < 0 ? 'negative' : ''}">
                                ${vectorTrend.change_7d >= 0 ? '+' : ''}${vectorTrend.change_7d || 0} this week
                            </span>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-title">Recent Workflow Runs</div>
                    ${githubError && !githubRuns.length
                        ? '<p style="color: #888; font-size: 0.9rem; padding: 10px 0;">' + githubError + '</p>'
                        : githubRuns.length
                            ? githubRuns.map(run =>
                                '<div class="workflow-run">' +
                                    '<span class="status-badge run-status ' + getStatusBadgeClass(run.status, run.conclusion) + '">' +
                                        getStatusText(run.status, run.conclusion) +
                                    '</span>' +
                                    '<div class="run-info">' +
                                        '<div class="run-name">' + escapeHtml(run.name) + '</div>' +
                                        '<div class="run-time">' + formatRelativeTime(run.created_at) + '</div>' +
                                    '</div>' +
                                    '<span class="run-duration">' + run.duration_text + '</span>' +
                                    '<a href="' + run.html_url + '" target="_blank" rel="noopener">View →</a>' +
                                '</div>'
                            ).join('')
                            : '<p style="color: #888; font-size: 0.9rem; padding: 10px 0;">No workflow runs found</p>'
                    }
                </div>
            `;
        }

        function renderAnalytics() {
            const trends = dashboardData.search_trends || [];
            const hourly = dashboardData.hourly_distribution || {};

            document.getElementById('analytics').innerHTML = `
                <div class="grid-2">
                    <div class="card">
                        <div class="card-title">Search Volume (30 Days)</div>
                        <div class="chart-container">
                            <canvas id="trendsChart"></canvas>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-title">Searches by Hour (7 Days)</div>
                        <div class="chart-container">
                            <canvas id="hourlyChart"></canvas>
                        </div>
                    </div>
                </div>
            `;

            // Trends chart
            const trendsCtx = document.getElementById('trendsChart').getContext('2d');
            new Chart(trendsCtx, {
                type: 'line',
                data: {
                    labels: trends.map(t => t.date),
                    datasets: [{
                        label: 'Searches',
                        data: trends.map(t => t.count),
                        borderColor: '#1e3a5f',
                        backgroundColor: 'rgba(30, 58, 95, 0.1)',
                        fill: true,
                        tension: 0.3
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: { legend: { display: false } },
                    scales: { y: { beginAtZero: true } }
                }
            });

            // Hourly chart
            const hours = Array.from({length: 24}, (_, i) => i.toString().padStart(2, '0'));
            const hourlyCtx = document.getElementById('hourlyChart').getContext('2d');
            new Chart(hourlyCtx, {
                type: 'bar',
                data: {
                    labels: hours.map(h => `${h}:00`),
                    datasets: [{
                        label: 'Searches',
                        data: hours.map(h => hourly[h] || 0),
                        backgroundColor: '#1e3a5f'
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: { legend: { display: false } },
                    scales: { y: { beginAtZero: true } }
                }
            });
        }

        function renderContent() {
            const zeroResults = dashboardData.zero_result_queries || [];

            document.getElementById('content').innerHTML = `
                <div class="card">
                    <div class="card-title">Zero-Result Queries (Content Gaps)</div>
                    <p style="color: #666; margin-bottom: 15px;">These searches returned no results - consider adding content for these topics.</p>
                    ${zeroResults.length > 0 ? `
                        <table>
                            <thead><tr><th>Query</th><th>Times Searched</th><th>Last Searched</th></tr></thead>
                            <tbody>
                                ${zeroResults.map(q => `
                                    <tr>
                                        <td><strong>${escapeHtml(q.query)}</strong></td>
                                        <td>${q.count}</td>
                                        <td>${q.last_searched ? new Date(q.last_searched).toLocaleDateString() : 'N/A'}</td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                    ` : '<p style="color: #888;">No zero-result queries - great coverage!</p>'}
                </div>
            `;
        }

        function renderTools() {
            document.getElementById('tools').innerHTML = `
                <div class="grid-2">
                    <div class="card">
                        <div class="card-title">Query Debugger</div>
                        <p style="color: #666; margin-bottom: 15px;">Test a search query and see raw Pinecone results with similarity scores.</p>
                        <div class="input-group">
                            <input type="text" id="debugQuery" placeholder="Enter a search query..." onkeypress="if(event.key==='Enter')debugSearch()">
                            <button class="btn" onclick="debugSearch()">Debug</button>
                        </div>
                        <div id="debugResults"></div>
                    </div>
                    <div class="card">
                        <div class="card-title">Health Check</div>
                        <p style="color: #666; margin-bottom: 15px;">Run detailed health checks on all services with latency measurements.</p>
                        <button class="btn" onclick="runHealthCheck()">Run Health Check</button>
                        <div id="healthResults" style="margin-top: 15px;"></div>
                    </div>
                </div>
            `;
        }

        function renderErrors() {
            const errors = dashboardData.error_log || [];

            document.getElementById('errors').innerHTML = `
                <div class="card">
                    <div class="card-title">Error Log (Last 20)</div>
                    ${errors.length > 0 ? errors.slice().reverse().map(e => `
                        <div class="error-item">
                            <div class="error-time">${new Date(e.timestamp).toLocaleString()}</div>
                            <div class="error-endpoint">${escapeHtml(e.endpoint)}</div>
                            <div>${escapeHtml(e.error)}</div>
                            ${e.details && Object.keys(e.details).length > 0 ? `<div style="color: #666; font-size: 0.85rem; margin-top: 5px;">${JSON.stringify(e.details)}</div>` : ''}
                        </div>
                    `).join('') : '<p style="color: #888;">No errors logged - system running smoothly!</p>'}
                </div>
            `;
        }

        async function loadVideos() {
            document.getElementById('videos').innerHTML = '<div class="card"><p>Loading sample videos...</p></div>';
            try {
                const res = await fetch('/api/v1/admin/sample-videos');
                const data = await res.json();
                document.getElementById('videos').innerHTML = `
                    <div class="card">
                        <div class="card-title">Sample Indexed Videos (${data.count} shown)</div>
                        <p style="color: #666; margin-bottom: 15px;">${data.note}</p>
                        <div class="video-grid">
                            ${data.videos.map(v => `
                                <a href="${v.youtube_url}" target="_blank" class="video-card" style="text-decoration: none; color: inherit;">
                                    <img src="${v.thumbnail_url}" alt="${escapeHtml(v.title)}" onerror="this.src='https://via.placeholder.com/320x180?text=No+Thumbnail'">
                                    <div class="video-card-info">
                                        <div class="video-card-title">${escapeHtml(v.title)}</div>
                                    </div>
                                </a>
                            `).join('')}
                        </div>
                    </div>
                `;
            } catch (e) {
                document.getElementById('videos').innerHTML = `<div class="card">Error loading videos: ${e.message}</div>`;
            }
        }

        async function debugSearch() {
            const query = document.getElementById('debugQuery').value.trim();
            if (!query) return;

            document.getElementById('debugResults').innerHTML = '<p>Searching...</p>';

            try {
                const res = await fetch('/api/v1/admin/debug-search', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ query, top_k: 10 })
                });
                const data = await res.json();

                document.getElementById('debugResults').innerHTML = `
                    <div class="debug-result">
                        <strong>Query:</strong> ${escapeHtml(data.query)}<br>
                        <strong>Model:</strong> ${data.embedding_model} (${data.embedding_dimensions}d)<br>
                        <strong>Results:</strong> ${data.count}<br><br>
                        ${data.results.map((r, i) => `
                            <div style="margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #ddd;">
                                <strong>#${i+1}</strong> Score: <span style="color: #1e3a5f;">${r.score}</span><br>
                                <strong>Video:</strong> ${escapeHtml(r.metadata.video_title || 'N/A')}<br>
                                <strong>Time:</strong> ${r.metadata.start_timestamp || '0:00'}<br>
                                <strong>Text:</strong> ${escapeHtml((r.metadata.text || '').substring(0, 200))}...
                            </div>
                        `).join('')}
                    </div>
                `;
            } catch (e) {
                document.getElementById('debugResults').innerHTML = `<div class="error-item">Error: ${e.message}</div>`;
            }
        }

        async function runHealthCheck() {
            document.getElementById('healthResults').innerHTML = '<p>Running health checks...</p>';

            try {
                const res = await fetch('/api/v1/admin/health-check');
                const data = await res.json();

                document.getElementById('healthResults').innerHTML = `
                    <div style="margin-bottom: 10px;">
                        <span class="status-badge ${data.overall === 'healthy' ? 'status-healthy' : 'status-error'}">
                            Overall: ${data.overall}
                        </span>
                    </div>
                    ${Object.entries(data.services).map(([name, info]) => `
                        <div class="metric-row">
                            <span class="metric-label">${name}</span>
                            <span class="metric-value">
                                <span class="status-badge ${info.status === 'healthy' ? 'status-healthy' : 'status-error'}">${info.status}</span>
                                ${info.latency_ms ? ` ${info.latency_ms}ms` : ''}
                            </span>
                        </div>
                    `).join('')}
                `;
            } catch (e) {
                document.getElementById('healthResults').innerHTML = `<div class="error-item">Error: ${e.message}</div>`;
            }
        }

        async function clearCache() {
            if (!confirm('Clear all caches? This will temporarily slow down repeated searches.')) return;

            try {
                await fetch('/api/v1/admin/clear-cache', { method: 'POST' });
                alert('Caches cleared successfully');
                loadDashboard();
            } catch (e) {
                alert('Error clearing cache: ' + e.message);
            }
        }

        function escapeHtml(text) {
            if (!text) return '';
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML;
        }

        loadDashboard();
        setInterval(loadDashboard, 60000);
    </script>
</body>
</html>'''


@app.route('/admin')
@require_admin_auth
def admin_dashboard():
    """Serve admin dashboard."""
    return ADMIN_HTML


# =============================================================================
# STATIC ROUTES
# =============================================================================

@app.route('/')
def home():
    """Serve search interface."""
    return send_from_directory('static', 'index.html')


# Legacy routes for backward compatibility
@app.route('/search', methods=['POST'])
@optional_api_key
@rate_limit(per_minute=30, per_hour=200)
def legacy_search():
    return search()


@app.route('/summarize', methods=['POST'])
@optional_api_key
@rate_limit(per_minute=10, per_hour=50)
def legacy_summarize():
    return summarize_results()


@app.route('/health', methods=['GET'])
def legacy_health():
    return health_check()


@app.route('/stats', methods=['GET'])
def legacy_stats():
    return get_stats()


# =============================================================================
# STARTUP
# =============================================================================

if __name__ == '__main__':
    # Initialize analytics database
    init_analytics_db()
    
    print()
    print("=" * 60)
    print(f"🎬 {CHANNEL_DISPLAY_NAME} YouTube Search API")
    print("=" * 60)
    print()
    print(f"Channel:   {CHANNEL_DISPLAY_NAME} ({CHANNEL_HANDLE})")
    print(f"Pinecone:  {PINECONE_INDEX} / {PINECONE_NAMESPACE}")
    print()
    print("Endpoints:")
    print(f"  GET  http://localhost:{SERVER_PORT}/           - Search UI")
    print(f"  GET  http://localhost:{SERVER_PORT}/admin      - Admin Dashboard")
    print(f"  POST http://localhost:{SERVER_PORT}/api/v1/search")
    print(f"  POST http://localhost:{SERVER_PORT}/api/v1/summarize")
    print(f"  GET  http://localhost:{SERVER_PORT}/api/v1/health")
    print(f"  GET  http://localhost:{SERVER_PORT}/api/v1/stats")
    print()
    print("=" * 60)
    print()
    
    app.run(host='0.0.0.0', port=SERVER_PORT, debug=True)
